### ISSUE TITLE
Doesn't seem to pick up pyproject.toml

### ISSUE THREAD

**Issue by jaredmcdonald** [mikehoyio/atom-python-black#11]
First off, thanks for your work on this package!

I have some configuration for our Black installation in a `pyproject.toml` file, as [recommended by the docs](https://black.readthedocs.io/en/stable/pyproject_toml.html). This works fine in regular CLI usage, but when I save a file, the default set of options is applied. (The easiest way to replicate this is to just set line length to something other than 88 in the config file, run Black on the CLI, and then save a file and note that the longer lines change).

Since Black config is fairly minimal it wouldn't be that terrible to keep in sync with the editor options, but it makes it more difficult to implement across a whole team. Also, some options aren't supported (e.g., `exclude`, `py36`, etc.).

One quick possibility that would solve this is just supporting Black's `--config` option (a path to a `pyproject.toml`), but I wonder if there's some way to instruct the plugin to evaluate the command within the project directory so that it picks up the config file. I don't have any experience with Atom packages but would be happy to dig around and see if I can figure this out, if this seems like something you want to support.

**Comment by danielcrane** [comment]
Was support for `exclude` ever added? I can't seem to get it to work.
