### ISSUE TITLE
Absorb hauntsaninja/atom-black

### ISSUE THREAD

**Issue by hauntsaninja** [mikehoyio/atom-python-black#5]
Hello! Being bad at googling things, I recently created my own Atom plugin for Black over at https://github.com/hauntsaninja/atom-black/ and submitted https://github.com/ambv/black/pull/456 to link the plugin in the editor integrations section of Black's README. However, it has since been pointed out that your plugin already exists.

There's no sense in having two plugins, so I propose I archive my plugin, and resolve https://github.com/ambv/black/pull/474 by linking over here. However, my plugin has some useful features that I'd like to see before I’d be willing to do so:

1. Helpful notifications on failure
2. Handling unsaved files
3. Faster toggling of "format on save" than going to the Settings page

Let me know what you think!

**Comment by mikehoyio** [comment]
Hey, 

This sounds like a great idea. Thank you for being very reasonable.

I'll be able to spend some time on this next week.
I look forward to collaborating with you!

Cheers
Mike

**Comment by mikehoyio** [comment]
Hey @hauntsaninja ,

I've now merged the improvements from atom-black into python-black!
Let me know what you think.
I've also opened up a pull request to update the black documentation.

Cheers
Mike
