### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by zach-nervana** [mikehoyio/atom-python-black#7]
i'm sorry this is vague, i would be happy to help debug. this package installed, however it seems to do nothing. i try using the enabled key binding, with no effect. when i open the command pallet, `black` reveals no commands. As far as i can tell there are no error messages.

**Comment by mikehoyio** [comment]
Hey,

Can you confirm you have `black` installed and are able to run it from the command line?

Cheers
Mike
