### ISSUE TITLE
Suppress error messages

### ISSUE THREAD

**Issue by bindlock** [mikehoyio/atom-python-black#8]
Hey. Thanks for your work.

Could I ask for suppress error message or add such option in configuration? Sometimes I save broken code and plugin react on it.

**Comment by mikehoyio** [comment]
Hey,

Yes I like this idea. Will add a toggle in the settings to supress error messages. On holiday this week so I'll have time to tackle this on the weekend.

Cheers
Mike

**Comment by piccolbo** [comment]
Thanks, adding only that I have autosave on so saving code in broken state is unavoidable, hence I have a constant cascade of red stuff on the right side of the screen, considering duct taping something over it :(

**Comment by mikehoyio** [comment]
Sorry it's taken a lot of time for me to get to this. Please checkout the latest release to see options for controlling error messages.

**Comment by piccolbo** [comment]
Don't see any error opts in 0.6.0. Atom reports up-to-date.

**Comment by mikehoyio** [comment]
Just this second updated it. 0.7.0 should be the version. Maybe it takes a little time for them to push it out everywhere.

**Comment by piccolbo** [comment]
Ok thanks
